version: "3.1"

services:
  mailer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: itisenricofermi/archivio-digitale-mailer
    secrets:
      - user
      - password
    ports:
      - 5000:80
    environment:
      - PORT=465
      - USER_FILE=/run/secrets/user
      - PASSWORD_FILE=/run/secrets/password
      - SERVER=smtp.ionos.com
      - FROM=Archivio Digitale <me@riccardosangiorgio.com>
      - SECURE=true

secrets:
  user:
    file: user-test.txt
  password:
    file: password-test.txt

